{% set version = "0.4.0" %}
{% set gh_org = "audreyr" %}
{% set gh_repo = "binaryornot" %}


package:
  name: {{ gh_repo }}
  version: {{ version }}

source:
  fn: {{ gh_repo }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ gh_repo[0] }}/{{ gh_repo }}/{{ gh_repo }}-{{ version }}.tar.gz
  sha256: ab0f387b28912ac9c300db843461359e2773da3b922ae378ab69b0d85b288ec8

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - chardet

test:
  requires:
    - coverage
    - hypothesis
    - python
  commands:
    - cd "{{ environ["SRC_DIR"] }}"
    - python setup.py test

about:
  home: https://github.com/{{ gh_org }}/{{ gh_repo }}
  license: BSD-3-Clause
  summary: >
            Ultra-lightweight pure Python package to check if a file is binary
            or text.

extra:
  recipe-maintainers:
    - bollwyvl
