{% set version = "0.4.4" %}
{% set gh_org = "audreyr" %}
{% set gh_repo = "binaryornot" %}


package:
  name: {{ gh_repo }}
  version: {{ version }}

source:
  fn: {{ gh_repo }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ gh_repo[0] }}/{{ gh_repo }}/{{ gh_repo }}-{{ version }}.tar.gz
  sha256: 359501dfc9d40632edc9fac890e19542db1a287bbcfa58175b66658392018061

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - chardet

test:
  source_files:
    - .
  requires:
    - coverage
    - hypothesis
    - python {{ python_min }}
    - setuptools
  commands:
    - python setup.py test

about:
  home: https://github.com/{{ gh_org }}/{{ gh_repo }}
  license: BSD-3-Clause
  summary: >
            Ultra-lightweight pure Python package to check if a file is binary
            or text.

extra:
  recipe-maintainers:
    - bollwyvl
