{% set version = "0.5.0" %}

package:
  name: binaryornot
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/b/binaryornot/binaryornot-{{ version }}.tar.gz
  sha256: dcacb1343219da5fbbb7828a46b946768c6df07b65453195954cbbecf14c1c83

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - chardet
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - binaryornot
  commands:
    - pip check
    - python -c "import binaryornot; assert binaryornot.__version__ == '{{ version }}'"

about:
  home: https://github.com/audreyr/binaryornot
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Ultra-lightweight pure Python package to check if a file is binary or text.

extra:
  recipe-maintainers:
    - bollwyvl
